### ISSUE TITLE
Bulk Platform Icons for New Platforms to cover

### ISSUE THREAD

**Issue by smeubank** [getsentry/platformicons#160]
### Descriptions

There is an initiative to ensure we communicate that we cover more platforms with existing SDKs, or actually move forward with building dedicated new SDK. Regardless we will be creating new platforms for many of these in the next months, to guide developers on setting up Sentry for their respective platforms.

https://github.com/getsentry/sentry-docs/issues/9943

### Solution

Provide optimized SVGs which can be used for the following platform creation and other relevant location in the UI

```[tasklist]
### Tasks
- [x] Hono - https://hono.dev/
- [x] Qwik - https://qwik.dev/
- [x] Solid - https://www.solidjs.com/
- [x] SolidStart https://start.solidjs.com/
- [x] Lit - https://lit.dev/
- [x] Meteor - https://github.com/meteor/meteor
- [x] Backbone - https://github.com/jashkenas/backbone
- [x] Analog - https://analogjs.org/
- [x] open-next https://github.com/sst/open-next
- [x] Million.js https://million.dev/docs/
- [x] Alpine.js https://alpinejs.dev/start-here
- [x] Tauri - is this a rust and JS thing? XD https://github.com/timfish/sentry-tauri
- [x] Livewire - https://laravel-livewire.com/
- [x] Hydrogen https://shopify.dev/docs/custom-storefronts/hydrogen/getting-started future is questionable, based on remix
- [x] Sinatra - https://github.com/sinatra/sinatra
- [x] Padrino - https://github.com/padrino/padrino-framework
- [x] Hanami - https://github.com/hanami
- [x] Grape - https://github.com/ruby-grape/grape
- [x] Trailblazer - https://github.com/trailblazer/trailblazer
- [x] Active Admin - https://github.com/activeadmin/activeadmin
- [x] Magento - Maybe with this: https://github.com/justbetter/magento2-sentry
```

**Comment by Jesse-Box** [comment]
@smeubank we already have solid, backbone and sinatra.

**Comment by Jesse-Box** [comment]
@stephanie-anderson @smeubank, with release `5.10.10`, you'll have all the above icons.

Closing issue
